name: Deploy React App

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Create env
    #   run: |
    #       echo "REACT_APP_BASE_URL=https://node-production.chandanagold.biz/api/v1/" >> .env.development
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # Change this to your Node.js version
    - name: Install dependencies
      run: npm i --legacy-peer-deps

    - name: Build React app
      run: npm run build
